### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by mazisparrow** [Axosoft/vscode-gitlens#1684]
- Issue Type: `Bug`
- Extension Name: `gitlens`
- Extension Version: `11.6.1`
- OS Version: `Darwin x64 20.6.0`
- VS Code version: `1.61.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by eamodio** [comment]
Can you please add more detail as to the issue you are experiencing and/or the steps to reproduce it?

Also, if this issue is reproducible, can you please enable output channel logging by running from _GitLens: Enable Debug Logging_ from the command palette (`ctrl+shift+p` or `cmd+shift+p`). This will enable logging to the _GitLens_ and _GitLens (Git)_ channel in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the log from the both _GitLens_ and _GitLens (Git)_ channels.

**Comment by eamodio** [comment]
@joe733 GitLens views only show up when you have a repository opened -- do you still see the same issue then?

**Comment by joe733** [comment]
@eamodio ah, you're right, I should have noticed, my bad. It works well in a repository.

**Comment by fai814** [comment]
> This issue needs more information and has not had recent activity. Please provide the missing information or it will be closed in 7 days. Thanks!

Fai  fai
