### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by chrisbguillermo** [Axosoft/vscode-gitlens#1716]
- Issue Type: `Bug`
- Extension Name: `gitlens`
- Extension Version: `11.6.1`
- OS Version: `Darwin x64 21.1.0`
- VS Code version: `1.62.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by fai814** [comment]
VS代碼版本： 1.62.1

**Comment by chrisbguillermo** [comment]
It's unresponsive. It's taking unnecessarily too much time to run or activate.

**Comment by fai814** [comment]
Chris Guillermo ***@***.***> 於 2021年11月12日週五 上午4:47寫道：

**Comment by eamodio** [comment]
Can you please add more detail as to the issue you are experiencing and/or the steps to reproduce it?

Also, if this issue is reproducible, can you please enable output channel logging by running from _GitLens: Enable Debug Logging_ from the command palette (`ctrl+shift+p` or `cmd+shift+p`). This will enable logging to the _GitLens_ and _GitLens (Git)_ channel in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the log from the both _GitLens_ and _GitLens (Git)_ channels.
